version : '3'

services:
  load-balancer:
    image: haproxy
    ports:
      - "8080:8080"
    volumes: 
      - ./haproxy:/usr/local/etc/haproxy
    networks:
      - search_head


  server1:
    build: .
    networks:
      - search_head
    volumes: 
      - ./config.yml:/opt/search_head/config.yml

networks:
  search_head:
    driver: bridge